### PR TITLE
Update AssemblyFileVersion to 4.1.0.0

### LINKED ISSUE #129: Update AssemblyFileVersion to 4.1
Per title

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #129

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by adecler — APPROVED** [review]
LGTM

**Pull request merged**
