### PR TITLE
Add 6.3 upgrader

### LINKED ISSUE #229: Upgrade to 6.3
Upgrade versioning for 6.3 and lock down 6.2 versioning files

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #229

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check copyright-compliance
@BHoMBot check installer

**Review by desaiwangBH — APPROVED** [review]
Approved: Changes make sense in line with end of milestone procedure.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
