### PR TITLE
Added versioning for TaperedProfile adding interpolationOrder to serialised TaperedProfiles

### LINKED ISSUE #100: Versioning changes for TaperedProfile to include interpolationOrder

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #100 

### Test files

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FStructure%5FEngine%2FStructure%5FEngine%2DIssue2014%2DMapTaperedProfilesToBars

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@adecler we've hit a bit of a stumbling block with the deserialisation. Would you have some time to help? 

When trying to convert from `json`, we get the following error:
```
1. This component failed to run properly.
- Error: When using DictionaryRepresentation.Document key values must serialize as strings.
- Occured in  BH.Engine.Serialiser.BsonSerializers.BH_ObjectSerializer.SerializeDiscriminatedValue(BsonSerializationContext context, BsonSerializationArgs args, Object value, Type actualType)
     called from BH.Engine.Serialiser.BsonSerializers.BH_ObjectSerializer.Serialize(BsonSerializationContext context, BsonSerializationArgs args, Object value)
- Are you sure you have the correct type of inputs? Check their description for more details.
```

The `TaperedProfile` owns a `Dictionary<double, IProfile>` which we use to store the positions and profiles. I am not sure if that is causing an issue because it the object to upgrade is a `Dictionary<string, object>` and one of those `objects`  (the profiles) is a `Dictionary<double, IProfile>`. 

I've noticed if you connect the wires over and over, it does deserialise the `TaperedProfile` but fails for the `SteelSection`, returning the following error:
`1. The type BH.oM.Structure.SectionProperties.SteelSection is unknown -> data returned as custom objects.`
image


The test script is on the link above, you want `Versioning - Objects.gh`

**Comment by peterjamesnugent** [comment]
@IsakNaslundBh @adecler I've updated the script so it has both `TaperedProfile` and `SteelSection` objects, where the `SteelSection` owns a `TaperedProfile`. The `TaperedProfile` seems to deserialise correctly, the only issue is the `SteelSection`.

**Review by IsakNaslundBh — APPROVED** [review]
Code here seem to be correct and run as expected. Issues with the serialisation seem to have been with the convention for ReadOnlyDictionaries, and seem to be fixed with https://github.com/BHoM/BHoM_Engine/pull/2197.

image


Happy to approve the code in this PR, but will hold of merging til after the Engine PR has been merged

**Pull request merged**
