### PR TITLE
Avoid copying BHoM assemblies to BHoMUpgrader folder

### LINKED ISSUE #265: BHoMUpgrader73 builds too many assemblies
#### Description:

As in the title, instead of building only upgrader dlls, currently `BHoMUpgrader73` project also builds all BHoM dependencies. So instead of this:
image

We have that:
image

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #265

### Test files

Theoretically it should be enough if versioning check passed, but I also added a super simple manual test: just build [this branch](https://github.com/BHoM/BHoM/tree/Test-Versioning_Toolkit-%23265-AvoidCopyingBHoMAssemblies) => rebuild BHoM and Versioning_Toolkit => check if _C:\ProgramData\BHoM\Upgrades\BHoMUpgrader73_ gets populated as expected => run script from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FVersioning%5FToolkit%2F%23266%2DAvoidCopyingBHoMAssemblies).

### CODE REVIEW

**Comment by pawelbaran** [comment]
> Running the upgrader 7.3 from the console, does indeed give me an error for missing dll:

Yeah I saw it, but thought it is OK taken versioning is always preceded by a call to `LoadBHoMAssemblies()`, which loads all required dependencies - that, however, I have only verified in GH and Revit.

Out of curiosity, did you call `LoadBHoMAssemblies()` prior to running versioning in your console app @adecler? I would argue the upgrader does not need to work as a standalone app as it only has meaning in the context of BHoM, i.e. let's remove _MongoDB.Bson.dll_ from the upgraders to save a few MB in the installer size and ask the consumers to load BHoM before running versioning. Or is there a gap in my thinking?

**Comment by adecler** [comment]
Yes, the upgraders need to be able to work as stand alone. It worked within the BHoM only because `versionWithPipe` is currently set to false int the `ToNew` method.

**Comment by pawelbaran** [comment]
I pushed a fix @adecler - simply added the missing assemblies as dependencies to `BHoMUpgrader73` project.

**Comment by adecler** [comment]
Thanks @pawelbaran, that does the trick. A bit strange that the explicit copy of dependencies is needed while it isn't in the other ones but I wouldn't loose sleep over it when there is a straightforward fix. 

Final thing that might be good to do here while we have the chance: the `BHoMUpgrader` depends on `Reflection-Engine`, `Serialiser_Engine`, and `Versioning_Engine` but doesn't actually use them so it might be good to clean that up as well.

**Comment by pawelbaran** [comment]
I removed all BHoM dependencies from the upgrader now 👍

**Comment by adecler** [comment]
> I removed all BHoM dependencies from the upgrader now 👍

Thanks @pawelbaran , I don't see the commit though :-P.

**Comment by pawelbaran** [comment]
Lol of course, because I did not push it before closing the machine 😃 Done now, sorry.

**Pull request merged**
