### PR TITLE
Add support for the PostBuild to extract and copy over Dataset upgrades

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

Will compile without, but done in support of https://github.com/BHoM/BHoM_Engine/pull/2845
   
### Issues addressed by this PR

Enables the PostBuild to also copy across Dataset upgrades

### Test files

See link in Engine PR

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
> @IsakNaslundBh can I confirm that this PR would not necessitate any update required to either of the wiki procedures listed on this repository? I don't think there is from what I can see, but if you could cast an eye over and double check that'd be handy.

As it stands, without any tweaks to the verification, that is the case. Had a thought about if we want to get dataset versioning to be checked though by the Versioning verification. If we want to do that, some more tweaks to code as well as procedure is required. WOuld probably be good with a call!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
See review [here](https://github.com/BHoM/BHoM_Engine/pull/2845#pullrequestreview-1000995522)

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
