### PR TITLE
Fix versioning for Environment_Engine.Create.Layer and provide message for deleted FireProtection object

### LINKED ISSUE #144: MEP_oM: FireProtection doesn't have versioning
#### Description:
A `BH.oM.MEP.FireProtection` class was deleted in https://github.com/BHoM/BHoM/pull/1069. I can see that there is another `FireProtection` class in `BH.oM.Environment.SpaceCriteria` but ther eisn't an obvious match so not sure if it's the right fit.

#### Expected behaviour:
`BH.oM.MEP.FireProtection` from version 3.3 should deserialise correctly. If the conversion is not trivial, use a custom converter

#### Test file(s):
Here's an example of that class from 3.3:

```
{ "_t" : "BH.oM.MEP.FireProtection", "BHoM_Guid" : "5431dbf5-a496-464b-8ae9-d9a02f7c65f9", "Name" : "test", "Fragments" : [], "Tags" : [], "CustomData" : { "test" : "test" }, "OccupancyHazardType" : "test", "SprinklerCoverage" : 42.420000000000002 }
```

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #144 

### Additional comments
Check the results of `check-versioning` to see `FireProtection` is no longer recorded as an error on this branch under 3.3 failures compared to the `master` branches.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by michaelhoehn — APPROVED** [review]
This LGTM

**Pull request merged**
