### PR TITLE
Add 6.0 upgrader

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
- Locks the 5.3 upgrader.
 - Adds the 6.0 upgrader.
 - Adds versioning datasets for 5.3.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check core

**Review by pawelbaran — APPROVED** [review]
Approving based on comparison with https://github.com/BHoM/Versioning_Toolkit/pull/197/files

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
