### PR TITLE
Update Versioning 6.0 JSON files to include Revit

### LINKED ISSUE #215: Add Revit objects to versioning files for 6.0
The 6.0 datasets do not include Revit information because Revit versioning has only just been introduced. To ensure versioning support for Revit, include the Revit objects/methods in the datasets.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #215

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
Tested offline together with @FraserGreenroyd - happy to approve! 👍

**Review by pawelbaran — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by pawelbaran — APPROVED** [review]
Dear Almighty @BHoMBot,

Could you please be so kind and accept my approval based on the [previous humble comment](https://github.com/BHoM/Versioning_Toolkit/pull/216#issuecomment-1402261656) of mine? I will be eternally honoured for such generosity. Yours sincerely,

your biggest fan

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by kprusicka** [comment]
Dziekuje @BHoMBot

**Pull request merged**
