### PR TITLE
Support for Revit 2018 and 2019 removed

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Helps closing https://github.com/BHoM/Revit_Toolkit/issues/1412

### Test files

Standard test procedure.

### Additional comments

As discussed with @FraserGreenroyd, removal of items related to Revit 2018 and 2019 from Versioning check datasets was considered the best way to move forward.

Removal done based on the following Regex strings:
- `.*Revit.*_2018, Version.*`
- `.*Revit.*_2019, Version.*`

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check copyright-compliance
@BHoMBot check installer

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
All good from previous reviews, approving to merge for deployment and further testing via alphas.

**Pull request merged**
