### PR TITLE
Upgrader for 5.3

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Provides upgrade information for 5.3 and locks the 5.2 upgrader

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by jamesramsden-bh — APPROVED** [review]
Approved on the basis of the versioning check passing

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer, ready-to-merge

**Pull request merged**
