### PR TITLE
Add 5.1 upgrader and lock down 5.0 upgrader. Include versioning CI for 5.0

### LINKED ISSUE #182: Upgrade versioning to 5.1
Lock down the 5.0 versioning and prepare the 5.1 versioning upgrader per [this procedure](https://github.com/BHoM/Versioning_Toolkit/wiki/End-of-milestone-procedure)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #182

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4701482960

I am dispensating copyright-compliance as BHoMBot will be updating this automatically very soon and I want to avoid confusion with it.

**Comment by adecler** [comment]
The regular update looks good (once the build path was fixed) but might be worth having a quick chat on the reasons behind the changes from object to string before merging.

PS: I have updated procedure on the wiki and removed the `_oM` project from the list that needs an assembly file version update since that project doesn't exist anymore.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check copyright-compliance

**Review by IsakNaslundBh — APPROVED** [review]
LGTM now

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
