### PR TITLE
Add 7.2 upgrader

### LINKED ISSUE #253: Lock 7.1 and add 7.2
For the new milestone

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #253

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by travispotterBH — APPROVED** [review]
Makes sense for the required changes

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
