### PR TITLE
Add 7.0 upgrader

### LINKED ISSUE #236: Add 7.0 upgrader
And lock down 6.3, etc., following milestone procedures.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #236

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check copyright-compliance

**Review by albinber — APPROVED** [review]
Checks passed, code looks good. Approving

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
