### PR TITLE
CI/CD: Align with changes to Test_oM and Test_Engine

### LINKED ISSUE #138: CI/CD: Align with changes to Test_oM and Test_Engine

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
While not directly dependent, I recommend testing this PR with https://github.com/BHoM/BHoM_Engine/pull/2300 since it contains some minor changes to the serialisation that will influence the results here as well.

   
### Issues addressed by this PR

Closes #138

Aligns to the recent changes to Test_oM and Test_Engine. 

For now, the top method without argument is hardcoding the list of beta versions that are tested for convenience. I don't want to delete other existing datasets and I expect CI/CD to use `FromJsonDataset(string testFolder, string exceptions = "")` anyways. 

### Test files

Call the TestRunner with the `Versioning` parameter. Here's the result that I get:

```
PS C:\ProgramData\BHoM\Assemblies> .\TestRunner.exe Versioning

Versioning from json datasets generated with 1 previous beta versions of the BHoM.
1 errors and 0 warnings reported.
Inner results:
        Beta Version 3.3: 898 object types and 4125 methods.
        15 errors and 0 warnings reported.
        Inner results:
                BH.oM.CSharp.Variable
                Error: Result returned as CustomObject
                Inner results:
                        An error occurred while deserializing the Expression property of class BH.oM.CSharp.Variable: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
                        The type BH.oM.CSharp.Variable is unknown -> data returned as custom objects.
                BH.oM.Inspection.Audit
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.Inspection.Audit is unknown -> data returned as custom objects.
                BH.oM.MEP.FireProtection
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.FireProtection is unknown -> data returned as custom objects.
                BH.oM.MEP.SectionProperties.DuctSectionProperty
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.SectionProperties.DuctSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.SectionProperties.PipeSectionProperty
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.SectionProperties.PipeSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.SectionProperties.WireSectionProperty
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.SectionProperties.WireSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.Duct
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.Duct is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.DuctSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.Pipe
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.Pipe is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.PipeSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.FlowSystem
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.FlowSystem is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.Duct is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.DuctSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.WireSegment
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.WireSegment is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.WireSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.Wire
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.Wire is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.WireSegment is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.WireSectionProperty is unknown -> data returned as custom objects.
                BH.oM.Adapters.Radiance.Executables.Rpict
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.Adapters.Radiance.Executables.Rpict is unknown -> data returned as custom objects.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByMass
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByMass from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByVolume
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByVolume from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByArea
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByArea from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
```

All the failing cases have already been reported as issues so they should hopefully be fixed soon. See issues here:
https://github.com/BHoM/BHoM/issues/1158
https://github.com/BHoM/BHoM/issues/1159
https://github.com/BuroHappoldEngineering/Radiance_Toolkit/issues/256
https://github.com/BHoM/LifeCycleAssessment_Toolkit/issues/200

The only extra one is `BH.oM.CSharp.Variable`. I am not too sure why the assembly `System.Collections.Immutable` doesn't load in TestRunner while it loads perfectly fine in Grasshopper. Will investigate separately but not urgent.

### Additional comments
I will add a dataset for 4.0 soon but I am happy to do that on a separate PR if this is already merged.

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
I have now added the dataset from beta 4.0 and we already have quite a few objects and methods that have not been versioned properly. 

Here's the list:

#### Methods: 

```
BH.Engine.Forms.Convert.ToWPF(BH.oM.Forms.IControl, BH.oM.Forms.WindowLayoutSettings)
BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByArea(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.EnvironmentalProductDeclarationField)
BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByMass(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.EnvironmentalProductDeclarationField)
BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByVolume(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.EnvironmentalProductDeclarationField)
BH.Engine.LifeCycleAssessment.Query.GetEvaluationValue(BH.oM.Dimensional.IElementM, BH.oM.LifeCycleAssessment.EnvironmentalProductDeclarationField)
BH.Engine.LifeCycleAssessment.Query.GetFragmentQuantityType(BH.oM.Dimensional.IElementM)
BH.Engine.LifeCycleAssessment.Query.GetQuantityTypeValue(BH.oM.Dimensional.IElementM)
```

#### Objects:

```
BH.oM.Adapters.Radiance.Executables.Rpict
BH.oM.Forms.OutputCollection
BH.oM.Inspection.Audit
BH.oM.MEP.Equipment.MechanicalEquipment
BH.oM.MEP.Fixtures.AirTerminal
BH.oM.MEP.Fixtures.LightFixture
BH.oM.MEP.System.Dampers.VolumeDamper
BH.oM.Test.Results.TestResult
OutputTree`1
```

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by rolyhudson** [comment]
I have run the test for both datasets. In both 4.0 and 3.3 I see the same errors. In 4.0 I also see:
`BH.oM.Forms.OutputCollection`
`OutputTree '1`

I don't think there is any reason not to approve this as the test clearly works. Just erring cautiously.

<details>
  <summary>Output:</summary>
```
Versioning from json datasets generated with 2 previous beta versions of the BHoM.
2 errors and 0 warnings reported.
Inner results:
        Beta Version 4.0: 1027 object types and 4306 methods.
        18 errors and 0 warnings reported.
        Inner results:
                test
                Error: Result returned as CustomObject
                BH.oM.CSharp.Variable
                Error: Result returned as CustomObject
                Inner results:
                        An error occurred while deserializing the Expression property of class BH.oM.CSharp.Variable: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
                        The type BH.oM.CSharp.Variable is unknown -> data returned as custom objects.
                BH.oM.Forms.OutputCollection
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.Forms.OutputCollection is unknown -> data returned as custom objects.
                        The type OutputTree`1 is unknown -> data returned as custom objects.
                OutputTree`1
                Error: Result returned as CustomObject
                Inner results:
                        The type OutputTree`1 is unknown -> data returned as custom objects.
                BH.oM.Inspection.Audit
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.Inspection.Audit is unknown -> data returned as custom objects.
                BH.oM.MEP.Fixtures.AirTerminal
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.Fixtures.AirTerminal is unknown -> data returned as custom objects.
                BH.oM.MEP.Fixtures.LightFixture
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.Fixtures.LightFixture is unknown -> data returned as custom objects.
                BH.oM.MEP.System.Dampers.VolumeDamper
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.Dampers.VolumeDamper is unknown -> data returned as custom objects.
                BH.oM.MEP.Equipment.MechanicalEquipment
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.Equipment.MechanicalEquipment is unknown -> data returned as custom objects.
                BH.oM.Adapters.Radiance.Executables.Rpict
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.Adapters.Radiance.Executables.Rpict is unknown -> data returned as custom objects.
                BH.oM.Test.Results.TestResult
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.Test.Results.TestResult is unknown -> data returned as custom objects.
                BH.Engine.Forms.Convert.ToWPF
                Error: Returned null from json.
                Inner results:
                        Method ToWPF from { "_t" : "System.Type", "Name" : "BH.Engine.Forms.Convert, Forms_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByArea
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByArea from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByVolume
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByVolume from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByMass
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByMass from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Query.GetQuantityTypeValue
                Error: Returned null from json.
                Inner results:
                        Method GetQuantityTypeValue from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Query, LifeCycleAssessment_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Query.GetFragmentQuantityType
                Error: Returned null from json.
                Inner results:
                        Method GetFragmentQuantityType from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Query, LifeCycleAssessment_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Query.GetEvaluationValue
                Error: Returned null from json.
                Inner results:
                        Method GetEvaluationValue from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Query, LifeCycleAssessment_Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
        Beta Version 3.3: 898 object types and 4125 methods.
        15 errors and 0 warnings reported.
        Inner results:
                BH.oM.CSharp.Variable
                Error: Result returned as CustomObject
                Inner results:
                        An error occurred while deserializing the Expression property of class BH.oM.CSharp.Variable: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
                        The type BH.oM.CSharp.Variable is unknown -> data returned as custom objects.
                BH.oM.Inspection.Audit
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.Inspection.Audit is unknown -> data returned as custom objects.
                BH.oM.MEP.FireProtection
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.FireProtection is unknown -> data returned as custom objects.
                BH.oM.MEP.SectionProperties.DuctSectionProperty
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.SectionProperties.DuctSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.SectionProperties.PipeSectionProperty
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.SectionProperties.PipeSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.SectionProperties.WireSectionProperty
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.SectionProperties.WireSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.Duct
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.Duct is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.DuctSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.Pipe
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.Pipe is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.PipeSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.FlowSystem
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.FlowSystem is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.Duct is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.DuctSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.WireSegment
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.WireSegment is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.WireSectionProperty is unknown -> data returned as custom objects.
                BH.oM.MEP.Elements.Wire
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.MEP.System.Wire is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.WireSegment is unknown -> data returned as custom objects.
                        The type BH.oM.MEP.System.SectionProperties.WireSectionProperty is unknown -> data returned as custom objects.
                BH.oM.Adapters.Radiance.Executables.Rpict
                Error: Result returned as CustomObject
                Inner results:
                        The type BH.oM.Adapters.Radiance.Executables.Rpict is unknown -> data returned as custom objects.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByMass
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByMass from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByVolume
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByVolume from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
                BH.Engine.LifeCycleAssessment.Compute.EvaluateEnvironmentalProductDeclarationByArea
                Error: Returned null from json.
                Inner results:
                        Method EvaluateEnvironmentalProductDeclarationByArea from { "_t" : "System.Type", "Name" : "BH.Engine.LifeCycleAssessment.Compute, LifeCycleAssessment_Engine, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" } failed to deserialise.
```
</details>

**Comment by adecler** [comment]
@rolyhudson , yes I have them too. Just my copy/paste skills that need some work 😄

**Comment by adecler** [comment]
I have added the upgrader for `TestResult`. Here's the json from beta 4.0 if you want to test it individually:

```
{ "_t" : "BH.oM.Test.Results.TestResult", "Description" : "test", "Status" : "CriticalFail", "Events" : [{ "_t" : "BH.oM.Reflection.Debugging.Event", "BHoM_Guid" : "b050acd8-1533-4042-a6b4-6e289e99f871", "Name" : "test", "Fragments" : [], "Tags" : [], "CustomData" : { "test" : "test" }, "Time" : { "$date" : -62135596800000 }, "UtcTime" : { "$date" : -62135596800000 }, "StackTrace" : "test", "Message" : "test", "Type" : "Note" }] }
```

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Review by rolyhudson — APPROVED** [review]
Checked the TestResult upgrade. All looks good to me.

**Pull request merged**
