### PR TITLE
Update csproject files to build locations for release mode

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes a CI issue when building beta artefacts that was identified at the end of last milestone.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by emilsvedjer — APPROVED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
