### PR TITLE
Versioning of Revit_Toolkit changes made in #1127

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #

### Test files

See https://github.com/BHoM/Revit_Toolkit/pull/1127.

### CODE REVIEW

**Review by michal-pekacki — APPROVED** [review]
LGTM 👍

**Comment by pawelbaran** [comment]
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check core
@BHoMBot check serialisation

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
