### PR TITLE
Uptick to 5.2 - new upgrader plus lock 5.1 upgrader

### LINKED ISSUE #188: Add 5.2 upgrader
For the new milestone

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #188

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by jamesramsden-bh — DISMISSED** [review]
Approved via conversation with @FraserGreenroyd as part of new milestone process

**Comment by jamesramsden-bh** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am request neutral checks on: core, copyright-compliance, installer, ready-to-merge

**Review by jamesramsden-bh — APPROVED** [review]
Approved in conversation with @FraserGreenroyd

**Pull request merged**
