### PR TITLE
Add custom upgrader for TributaryRegion

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Adding custom upgrader for TributaryRegion

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Owing to approving reviews on dependent PRs and versioning passing, I am approving this PR for @IsakNaslundBh to merge with the other PRs which provide the functionality changes and reviews.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
