### PR TITLE
Attempt to load Revit API if needed/existing in PostBuild

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
As discussed with @pawelbaran during testing of Revit Versioning.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check versioning
@BHoMBot check copyright-compliance

**Review by pawelbaran — APPROVED** [review]
Happy to approve the change based on the discussion and testing made together with @FraserGreenroyd over the last 2 days 👍

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, ready-to-merge

**Pull request merged**
