### PR TITLE
Adding support for method upgrade

### LINKED ISSUE #7: Add support for method upgrade

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 
- ~~While it doesn't depend on it, it is good to have https://github.com/BHoM/BHoM_Engine/pull/1335 on as it will make it easier for you to add new method conversions in the `ToNewMethod` dictionary.~~  
That engine PR is already merged. Thanks Fraser.
- Kind of depends on https://github.com/BHoM/BHoM_UI/pull/167 but only for testing purposes. 
   
### Issues addressed by this PR

Closes #7

### Test files
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Versioning_Toolkit/Issue7_MethodUpgradeTest_ForAdapters.gh?csf=1&e=Su4xfT

You will need the following PRs to test this file correctly:
- BHoM/BHoM_Adapter#164
- https://github.com/BHoM/BHoM_UI/pull/167
- https://github.com/BHoM/Grasshopper_Toolkit/pull/440
- https://github.com/BHoM/Socket_Toolkit/pull/57

### Additional comments
- This has been done within the context of the interface change for the adapters. So the test files focuses on that.
- Methods are a bit more tricky than objects because it is not about recovering the content the best we can this time. It is about finding a method that does the same thing even if the inputs/outputs are different. This is why I haven't changed the method deserialiser in the serialise engine to automatically return the new version of the method. This time I want it to keep failing so the UI get a chance to use the rest of its information (i.e. old input/output parameters) to upgrade the component correctly (i.e. reorganise the inputs).
- Notice that we now have full support for upgrading objects, methods, and namespaces/types. The last two are in a single file (something that we might want to change ?) while the first one is in a folder. I have therefore modified the folder name to `Object Converter` to clarify the relation with the other two files. Happy for ideas on how better organise the whole thing. Keep in mind though that most of this content (at least types and methods) should be filled automatically through refactoring via the VisualStudio_Toolkit in the medium term. 
- I have left the upgrade methods for the adapter in the PR for testing purposes. Those will have to be commented out if merged before the PRs for the level 4 changes on the adapter (more specifically the UI PR)

### CODE REVIEW

**Comment by adecler** [comment]
@pawelbaran , I have added you as a reviewer so you can already give your feedback in preparation of https://github.com/BHoM/Revit_Toolkit/issues/450

**Comment by FraserGreenroyd** [comment]
@alelom I feel you should take a look at this PR if you can as it is focusing on adapter versioning.

I intend to try and look at it today, but I am cautious of the fact I have reviewed the past couple of versioning PRs and would be good to spread the knowledge to others as well, so @IsakNaslundBh or @epignatelli it would be good if you can take a look today as well? :smile:

**Comment by epignatelli** [comment]
This depends on a draft pr for testing - is this actually to review?

**Comment by alelom** [comment]
It seems some files are missing and that's blocking compilation for me:
image

**Comment by adecler** [comment]
@alelom , sorry about that, it seems that the project file was not pushed properly last time. Now fixed

@epignatelli , yes it is. But we will have to remove the content of the `ToNewMethod` dictionary (and the dependency of course) before merging (See my last additional comment). I will add the `do-not-merge` label to reinforce that.

**Comment by alelom** [comment]
Thanks for that @adecler. I can now compile successfully.

I now aligned both this PR and https://github.com/BHoM/Socket_Toolkit/pull/57 to the latest changes in BHoM/BHoM_Adapter#164.

However, on opening of GH, I get this:


and on the opening of the test script:


Something about my latest changes must've broken it somehow.
The latest changes I've made are rather small, if compared to the refactor I had done up to the point you wrote this -- I can't figure out where the issue is arising.

I'd appreciate if we could have a look at this together. I'm also happy to have a Skype if you think it's quicker.

**Comment by adecler** [comment]
@alelom , yes, let's try to have a chat when you get to the office (assuming you don't get there too late 😋 )

**Comment by alelom** [comment]
The errors at https://github.com/BHoM/Versioning_Toolkit/pull/8#issuecomment-561720449 were caused by an issue in the Engine, now corrected by https://github.com/BHoM/BHoM_Engine/pull/1377

**Comment by adecler** [comment]
Thanks @alelom , it was actually a bug on the Grasshopper side. If you re-sync and recompile that part, it should now work fine for the pull.

**Pull request merged**
