### PR TITLE
Adding versioning for Lighting results

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1391
   
### Issues addressed by this PR

Adding custom converters for classes changed in the oM

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check copyright-compliance

**Review by enarhi — APPROVED** [review]
LGTM

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
