### PR TITLE
Changes for 7.3 milestone

### LINKED ISSUE #263: Add upgrader and test dataset for 7.3
#### Suggestions to restore compliance:

Follow end of milestone procedure for 7.3 milestone start

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #263

- Add new upgrader
- Freeze upgrade file from previous version
- Add new test sets for 7.2
- Change versions in verification

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check copyright-compliance
@BHoMBot check installer

**Review by adecler — APPROVED** [review]
Approving based on 
 - Review of the code changes themselves
 - Units tests are passing
 - Bot checks are passing

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
