### PR TITLE
Upgrade floor design

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

In support of
https://github.com/BuroHappoldEngineering/StructuralEngineering_Toolkit/pull/498
   
### Issues addressed by this PR

Add custom upgrader for FloorDesign objects and FloorConfigurations

### CODE REVIEW

**Review by Chrisshort92 — APPROVED** [review]
Approved

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check copyright-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
