### PR TITLE
Provide an upgrade system for serialised objects

### LINKED ISSUE #1: Versioning_Engine: Provide an upgrade system for serialised objects
Objects already stored as Json/Bson in a database, a component, or a file need to upgrade themselves automatically when deserialised. 

Provide a solution for a single level of upgrade (i.e no chaining of upgraders required at this stage)

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR
Closes #1

As described in the issue, this focus of upgrading deprecated objects from a single generation ago. I think it will make more sense to take care of the chain of upgraders when we reach next quarter. The system is ready to support it though.

Here's how the system is organised:
- One `BHoMUpgraderXY.exe` for each version X.Y of the code. Each loading its own set of dll corresponding to that version (i.e. the version at the end of the quarter that contains both the deprecated definitions and the new ones). Those only contain the methods that convert to new or old objects.
- Their Program method will mainly call the generic Upgrader from `BHoMUpgrader.dll`. This is the one that will listen for upgrade requests and call the converter.
- The only part that is tied to the UI (i.e. loaded there) is the Versioning_Engine. AS soon as the `ToNewVersion` method is called, it will start (if not already) the proper upgrader exe and send it the object to upgrade via a Pipe (so that old dlls require by an upgrader are not loaded in the UI). 

I hope that is at least a little bit clear.

### Test files

I have added a temporary `Versioning_oM` project that is only here to allow you to create your own (deprecated) classes for testing. I have done a few as example. Notice that you will need to create your `ToNew` and `ToOld` methods in the converter of `BHoMUpgrader30`. 

Below an example of tests I have already done but make sure you test whatever user case come to your mind.

image

### Additional comments
- You will need to corresponding PR for the Serialiser_Engine to be able to test via `FromJson`.
- Once you are happy with this PR, I suggest we remove the oM and the test convert methods before merging.
- There is more to come on the backward compatibility but i think this is a good first PR. This is already a decently big one to review as it is given the technical aspect of it.

### CODE REVIEW

**Comment by adecler** [comment]
If we ignore the temporary oM project (there only for testing), this isn't a diamond so it might be good to change the name of this repo so it doesn't contain `Toolkit`

**Comment by al-fisher** [comment]
> If we ignore the temporary oM project (there only for testing), this isn't a diamond so it might be good to change the name of this repo so it doesn't contain Toolkit

Makes sense - two initial thoughts:
- Might there be future further development that might expand the scope of this repo and thus simply calling it a __Toolkit_ leaves room for flexibility.
- Additionally  (with split of Versioning_Engine over to BHoM_Engine also) perhaps worth revisiting the naming of the Upgrader.exes and naming the repo also to reflect their primary focus.

**Comment by adecler** [comment]
It is worth clarifying what kind of upgrades are covered by this PR. 

In general, we can divide a change to a class definition in 3 broad categories:

- The class is marked as deprecated and is replaced with a new class definition. This would be the case if we change the inside of the class and its namespace/name.
- The namespace is changed but the inside of the class isn't. In this case, we could use the deprecated attribute again but that means doing it for every single class inside that namespace.
- The namespace and name of the class don't change, only its internal definition. In that case we cannot use the deprecated attribute since there is not class with a different type that we can use as a replacement.

This PR only solves the first case. Admittedly, this is probably the least frequent scenario but was the most difficult to put in place. Hence this PR.  

The second case is way easier since we could just receive the fallback custom object (produced when serialisation fails) and replace its "_t" (i.e. type) property with the new one before converting to BHoM object.

The third case is more annoying but will require the infrastructure created in this PR so best to keep it for last.

I hope this clarifies a bit the scope of this PR and what you need to focus on when reviewing.

**Comment by al-fisher** [comment]
@adecler Happy to merge this to enable next phases of development as discussed above

**Pull request merged**
