### PR TITLE
Versioning for Rebar projects added

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check versioning

**Comment by pawelbaran** [comment]
@BHoMBot check core
@BHoMBot check compliance
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer, versioning, ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
It's not fun but it works so happy to merge for deployment in line with the other PRs removing Rebar.

**Pull request merged**
