### PR TITLE
BHoMUpgrader53: Add Converter methods for Revit_UI repo split

### PR DESCRIPTION
**Pull request by vietle-bh**
### NOTE: Depends on 

TBC
   
### Issues addressed by this PR

Added Converter methods for Revit_UI repo split

### Changelog

- Added Converter methods for Revit_UI repo split

### CODE REVIEW

**Comment by vietle-bh** [comment]
@BHoMBot check versioning

**Comment by vietle-bh** [comment]
@BHoMBot check versioning

**Comment by vietle-bh** [comment]
Sorry @FraserGreenroyd , the custom converter method fixed the versioning check on my machine but not here, probably because the check here doesn't see the same branch name under `Revit_UI`. It sees the branch under `BuroHappold_Revit_Toolkit` though. Do you know why?

**Comment by vietle-bh** [comment]
@BHoMBot check versioning

**Comment by vietle-bh** [comment]
@BHoMBot check versioning

**Comment by vietle-bh** [comment]
@BHoMBot check versioning

**Comment by vietle-bh** [comment]
@BHoMBot check versioning

**Comment by vietle-bh** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by vietle-bh** [comment]
@BHoMBot check versioning

**Comment by vietle-bh** [comment]
@BHoMBot check copyright-compliance 
@BHoMBot check core
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on code review and passing tests in line with the work undertaken by @vietle-bh

**Comment by vietle-bh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
