### PR TITLE
Add 7.1 upgrader

### LINKED ISSUE #245: Add 7.1 upgrader
Upgrade versioning for 7.1 and lock down 7.0 versioning files

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #245

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check installer

**Review by Tom-Kingstone — APPROVED** [review]
Approved after core+versioning check. Approved for next milestone

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
