### PR TITLE
Add 6.1 upgrader

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
- Locks the 6.0 upgrader.
 - Adds the 6.1 upgrader.
 - Adds versioning datasets for 6.0.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check core

**Comment by kprusicka** [comment]
Dziekuje @BHoMBot

**Pull request merged**
