### PR TITLE
Add Adapter Verification

### LINKED ISSUE #187: Verification: Versioning of Adapters is not tested by the verification
#### Definition of the test :

The current versioning test sets does not contain information about any of the Adapters and their constructors. Should either add a new testset with all constructors, or add them to the method checks.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #187 

Allows for Adapters to be checked when checking versioning.

Have added datasets for all adapters specifically since 3.3 onwards, and ensured they version correctly with updates to some upgrade files where appropriate.

The images below highlight the passes on local checks.

image
image

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 21317438055

**Review by Tom-Kingstone — APPROVED** [review]
After spot check of parts of the datasets, all seems to be in order. Approving for future versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
