### PR TITLE
Allow upgrader EXEs to also be DLLs

### LINKED ISSUE #255: Allow upgrader EXEs to also be referencable DLLs
For each upgrader project from 3.0 onwards, ensure the `exe` file is also accessible as a `dll` file independently. This is to allow for other people to build their own versioning toolkits without needing to either put versioning in this open source repository, or without forking this repository and trying to keep it up to date. This allows for others to build versioning toolkits on top of this toolkit and have access to existing versioning provided by this toolkit.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1610

### Issues addressed by this PR
Fixes #255

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check versioning
@BHoMBot check installer
@BHoMBot check copyright-compliance

**Review by Tom-Kingstone — APPROVED** [review]
Approved, as this will be more useful for doing versioning locally

**Pull request merged**
