### PR TITLE
Added versioning for TaperedProfile adding interpolationOrder to serialised TaperedProfiles

### LINKED ISSUE #100: Versioning changes for TaperedProfile to include interpolationOrder

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/992
https://github.com/BHoM/BHoM_Engine/pull/1980
   
### Issues addressed by this PR

Closes #100 

### Test files

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FStructure%5FEngine%2FStructure%5FEngine%2DIssue2014%2DMapTaperedProfilesToBars

### Additional comments

Not quite working as expected, I think this is because the `Profiles` is a `Dictionary<double,IProfile>` so it makes it a little more complicated.

### CODE REVIEW

**Comment by adecler** [comment]
Unfortunate timing. This is clashing with https://github.com/BHoM/Versioning_Toolkit/pull/101. Given that it was submitted 3 hours earlier, that PR has priority. I have marked this as 'do-not-merge' as you will have to wait for the other PR to be merged first.

**Comment by IsakNaslundBh** [comment]
> Not quite working as expected, I think this is because the Profiles is a Dictionary<double,IProfile> so it makes it a little more complicated.

good one @peterjamesnugent . Lets have a look later if we need any changes going from decimal to double.

**Comment by adecler** [comment]
Should this be resumed or has it been replaced with another PR ?

**Comment by peterjamesnugent** [comment]
Reraised here due to issues rebasing: https://github.com/BHoM/Versioning_Toolkit/pull/105

**Pull request closed without merging**
