### PR TITLE
Added LBT 5.3 converter methods

### LINKED ISSUE #206: Versioning for LadybugTools_Toolkit

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #206 

Many things changed in source PR, though only minor changes to objects between versions requiring conversion here.

### Changelog

- Added Converter methods for LBT_Toolkit Shelter and Typology objects

### Additional comments

Do not merge LadybugTools_Toolkit branch - it should be deleted once this PR gets tested & approved!

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by jamesramsden-bh** [comment]
@BHoMBot check copyright-compliance

**Comment by jamesramsden-bh** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
