### PR TITLE
Add 6.2 upgrader

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
- Locks the 6.1 upgrader.
 - Adds the 6.2 upgrader.
 - Adds versioning datasets for 6.1.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check core
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check versioning
@BHoMBot check installer

**Review by EKAdebo — APPROVED** [review]
Upticked as expected with versioning passing.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
