### PR TITLE
Upgrade CableTray

### LINKED ISSUE #161: Add support for CableTray modifications

### PR DESCRIPTION
**Pull request by michaelhoehn**
### Issues addressed by this PR

Closes #161

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Need versioning for the connection property too by the looks of it. Gimme a shout if help is needed :smile:

**Comment by tiagogrossi** [comment]
@BHoMBot check versioning

**Comment by tiagogrossi** [comment]
@BHoMBot check required

**Comment by michaelhoehn** [comment]
I'll be closing this PR and issuing a new one since we've just crossed into a new milestone.

**Pull request closed without merging**
