### PR TITLE
Switch to forward versioning

### LINKED ISSUE #132: Switch to forward versioning
#### Description:
The backward versioning we have is creating some issues when there is a need to chain multiple upgrades on objects older that 3 months (i.e. requiring upgrades through multiple upgraders).

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #132

As per title. After testing on all datasets from previous versions of the BHoM, This doesn't add additional fails to the master.

Here's the list of types that are now working with this PR:

#### version 3.3
```
BH.Engine.Geometry.Create.TaperedProfile
```

#### version 3.2

```
BH.Engine.Geometry.Create.TaperedProfile
BH.Engine.Structure.Query.AnalyticalBars
BH.Engine.Structure.Query.Geometry
BH.oM.Data.Collections.Graph`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Data_oM, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null
GraphLink`1
GraphNode`1
```

#### version 3.1

```
BH.Engine.Common.Query.Centroid
BH.Engine.Common.Query.IBounds
BH.Engine.Common.Query.IInternalOutlineCurves
BH.Engine.Environment.Query.PanelsByLevel
BH.Engine.Environment.Query.PanelsByMaximumLevel
BH.Engine.Environment.Query.PanelsByMinimumLevel
BH.Engine.Geometry.Create.TaperedProfile
BH.Engine.Plaxis.Convert.ToPlaxisRobotId
BH.Engine.Structure.Create.ConcreteSectionFromProfile
BH.Engine.Structure.Query.AnalyticalBars
BH.Engine.Structure.Query.Geometry
BH.oM.Physical.Elements.Beam
BH.oM.Physical.Elements.Bracing
BH.oM.Physical.Elements.Cable
BH.oM.Physical.Elements.Column
BH.oM.Physical.Elements.Pile
BH.oM.Physical.FramingProperties.ConstantFramingProperty
BH.oM.Structure.Elements.BowlStructure
BH.oM.Structure.SectionProperties.Reinforcement.LayerReinforcement
BH.oM.Structure.SectionProperties.Reinforcement.PerimeterReinforcement
BH.oM.Structure.SectionProperties.Reinforcement.TieReinforcement
Graph`1
GraphLink`1
GraphNode`1
```

#### version 3.0

```
BH.Engine.Common.Query.Centroid
BH.Engine.Common.Query.IBounds
BH.Engine.Common.Query.IInternalOutlineCurves
BH.Engine.Environment.Query.PanelsByLevel
BH.Engine.Environment.Query.PanelsByMaximumLevel
BH.Engine.Environment.Query.PanelsByMinimumLevel
BH.Engine.Structure.Create.ConcreteSectionFromProfile
BH.Engine.Structure.Modify.SetOutlineElements1D
BH.Engine.Structure.Query.AnalyticalBars
BH.Engine.Structure.Query.Geometry
BH.oM.Physical.Elements.Beam
BH.oM.Physical.Elements.Bracing
BH.oM.Physical.Elements.Cable
BH.oM.Physical.Elements.Column
BH.oM.Physical.Elements.Pile
BH.oM.Physical.FramingProperties.ConstantFramingProperty
BH.oM.Structure.Elements.BowlStructure
BH.oM.Structure.SectionProperties.Reinforcement.LayerReinforcement
BH.oM.Structure.SectionProperties.Reinforcement.PerimeterReinforcement
BH.oM.Structure.SectionProperties.Reinforcement.TieReinforcement
Graph`1
GraphLink`1
GraphNode`1
```

### Test files
You need to compare the result you get on this PR with the master and make sure that nothing that works on the master doesn't work here. I have prepared a list of files that test the datasets on each previous beta version version of the BHoM here: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Versioning_Toolkit/%23133-Forward%20Versioning?csf=1&web=1&e=Kf9igY

Note that you might have to change the list of reference items that don't work on the master since yo umight have thing on your machine that I don't. To do that, just run the scripts first on the master and copy paste the list of failing versioning into the `On master` panels. Then just rerun the script after compiling this PR. 

The only `Only on new` item you should have on any panel is `BH.Engine.Serialiser.Compute.AllowUpgradeFromBson` as that one was removed (we don't need the crazy back and forth between versioning and serialisation anymore).

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@adecler Versioning_Toolkit depends on `BHoM_UI` to build itself, according to `dependencies.txt` - so looking at the Azure failure, either `CSharp_Toolkit` needs adding to `dependencies.txt` or `BHoM_UI` needs removing :smile:

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@FraserGreenroyd , I have removed both `BHoM_UI` and `BHoM_Adapter` in the list of dependencies as there was no reference to either. The only thing that might be worth checking is that the versioning toolkit is still compiled last after this change.

**Comment by adecler** [comment]
@FraserGreenroyd , I have added the versioning for the replacement of the MEP node by geometry Point as well as the change of property name from `StartNode` and `EndNode` to `StartPoint` and `EndPoint`

This fixes those classes for me (assuming you already fixed the [`DuctMaterial` issue](https://github.com/BHoM/BHoM/issues/1158)):

```
BH.oM.MEP.Elements.Duct
BH.oM.MEP.Elements.FlowSystem
BH.oM.MEP.Elements.Node
BH.oM.MEP.Elements.Pipe
BH.oM.MEP.Elements.Wire
BH.oM.MEP.Elements.WireSegment
```

You're welcome 😉

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
## Introduction

The following notes are the steps which I have undertaken to test this PR and [the Serialisation_Engine one](https://github.com/BHoM/BHoM_Engine/pull/2269).

1. Download today's (210120) alpha and install as usual
2. Download and open each of the Versioning GH scripts from the linked SharePoint folder
3. Update the location of the CI datasets to my machine and run the script
4. Copy outputs to the 'on master' boxes
5. Compile BHoM_Engine and then Versioning_Toolkit and reopen the scripts
6. Compared the output differences

The following are my results. Where a section isn't covered, it can be assumed that both output panels did not contain any data for me to show.

## Results

### Versioning_30.gh

**Methods failing to deserialise**


**Objects returning CustomObject**


### Versioning_31.gh

**Methods failing to deserialise**
image

**Objects returning CustomObject**
Returned the same result as `Versioning_30.gh` (see above).

### Versioning_32.gh

**Methods failing to deserialise**
image

**Objects returning CustomObject**
image

### Versioning_33.gh

**Methods failing to deserialise**
image

**Objects returning CustomObject**
image

### Additional Scripts

I also opened the following scripts:

 - [Test versioning of create method Robot - v3.2](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/04_WIP%20Beta/0012_VersioningScripts/v3.2/Test%20versioning%20of%20create%20method%20Robot.gh?csf=1&web=1&e=dGtpnH) - this opened with no notable issues.

 - [ModelLaundery_Toolkit_Issue202Enable Versioning_Toolkit - v3.1](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/04_WIP%20Beta/0012_VersioningScripts/v3.1/ModelLaundery_Toolkit_Issue202Enable%20Versioning_Toolkit.gh?csf=1&web=1&e=3J7Jz6) - this opened with no notable issues

 - [Issue7_MethodUpgradeTest_ForAdapters - v3.0](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/04_WIP%20Beta/0012_VersioningScripts/v3.0/Issue7_MethodUpgradeTest_ForAdapters.gh?csf=1&web=1&e=fUIBED) - this opened reasonably well, see image below for only issue encountered.

image

## Conclusion

I believe this to be a reasonable test of the forward versioning work brought in by this PR. The results appear to be satisfactory to me, some issues for which issues have already been raised or are being processed in other manners I believe.

I am happy to approve this PR on the basis of this test, however, I will accept further judgement on my outputs by @adecler or @IsakNaslundBh if appropriate to double check there isn't anything massively untoward that would prevent us wanting to put this into an alpha for wider testing this milestone.

**Review by FraserGreenroyd — APPROVED** [review]
@adecler I will leave you to merge this if you are content with my remarks on the Serialisation_Engine PR :smile:

**Pull request merged**
